ALTER TABLE items ADD COLUMN custom_name VARCHAR(200);
ALTER TABLE items ADD COLUMN price NUMERIC(12, 2);
ALTER TABLE items ADD COLUMN is_owned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE items ALTER COLUMN period TYPE VARCHAR(200);
